### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by boringusername99** [tonycoco/heroku-buildpack-ember-cli#74]
I'm having issues when pushing to Heroku. See error log below. This seems similar to the most comment posted here: https://github.com/tonycoco/heroku-buildpack-ember-cli/issues/32

Of note is that when Googling around to solve this issue, some people mention that upgrading ember-cli to 0.2.0 solved the issue. I have ember-cli 0.2.1, but for some reason, the log below says it is trying to build with version 0.1.5.

I have tried performing all of the cleanup steps listed here:
https://github.com/ember-cli/ember-cli/releases/tag/v0.1.2

Here's my package.json:
> {
  "name": "weekendr-ember-cli",
  "version": "0.0.0",
  "description": "Small description for weekendr-ember-cli goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.12.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "ember-cli": "^0.2.1",
    "ember-cli-app-version": "0.3.2",
    "ember-cli-babel": "^4.0.0",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-htmlbars": "0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.9",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.15",
    "ember-export-application-global": "^1.0.2",
    "glob": "4.5.3",
    "rimraf": "2.2.8"
  }
}

Error log:
> emote: -----> Caching bower_components directory for future builds
remote: -----> Building Ember CLI application production distribution
remote:        version: 0.1.5
remote:        Could not find watchman, falling back to NodeWatcher for file system events
remote:        BuildingCleanup error.
remote:        undefined is not a function
remote:        TypeError: undefined is not a function
remote:            at Function.rimrafSync (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:262:13)
remote:            at ConfigLoader.CachingWriter.cleanup (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/broccoli-caching-writer/index.js:114:10)
remote:            at cleanupTree (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:128:19)
remote:            at /tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/broccoli/node_modules/promise-map-series/index.js:8:27
remote:            at $$$internal$$tryCatch (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
remote:            at $$$internal$$invokeCallback (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
remote:            at $$$internal$$publish (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
remote:            at $$rsvp$asap$$flush (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
remote:            at process._tickCallback (node.js:355:11)
remote:        Build failed.
remote:        undefined is not a function
remote:        TypeError: undefined is not a function
remote:            at rimraf (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:57:13)
remote:            at lib$rsvp$node$$tryApply (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1467:11)
remote:            at lib$rsvp$node$$handleValueInput (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1567:20)
remote:            at fn (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1555:18)
remote:            at /tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/broccoli-caching-writer/index.js:100:14
remote:            at lib$rsvp$$internal$$tryCatch (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:489:16)
remote:            at lib$rsvp$$internal$$invokeCallback (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:501:17)
remote:            at lib$rsvp$$internal$$publish (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:472:11)
remote:            at lib$rsvp$asap$$flush (/tmp/build_dcfcd05d5a5361ada76663c3e628272f/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1290:9)
remote:            at process._tickCallback (node.js:355:11)
remote:
remote:  !     Push rejected, failed to compile Ember CLI app
remote:
remote: Verifying deploy...
remote:
remote: !	Push rejected to murmuring-falls-8111.
remote:

**Comment by tonycoco** [comment]
Please see: https://github.com/tonycoco/heroku-buildpack-ember-cli#troubleshooting

**Comment by boringusername99** [comment]
Sorry, *facepalm*

I missed the last step of the troubleshooting (ember build) when I tried it before. Also discovered that I wasn't on the master branch and that I had forgotten to commit a few things. :) *sigh*

I still haven't figured out why my app works in local dev but just pulls up a blank page on heroku production, but at least it's deployed now. :) Feel free to close.

**Comment by tonycoco** [comment]
:) No prob!
